### ISSUE TITLE
VIP Membership / Chest

### ISSUE THREAD

**Issue by EasyTarget2** [sevin7676/SurvivalArenaTracking#59]
My son saw a new option to buy a vip chest with a free week and then .99/week after (it didn't appear in my shop in windows, he was using ios) He purchased the vip chest and got a verification email that it was successful and then when it switched back to the account it said his account had been banned.

**Comment by sevin7676** [comment]
This is the unofficial tracking... You need to report this to the devs to get his account fixed. Mention Alexanders in discord to get it fixed: https://discordapp.com/channels/306400684662718464/306400684662718464
